# Generated by Django 4.0.3 on 2022-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_remove_technician_id_alter_appointments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
