# Generated by Django 4.0.3 on 2022-08-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_appointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='vin',
            field=models.CharField(max_length=17),
        ),
    ]
